### ISSUE TITLE
Update Native Tokens Count to uint8

### ISSUE THREAD

**Issue by lzpap** [iotaledger/bee#1035]
## Description

`Native Tokens Count` field of outputs in [TIP-18](https://github.com/iotaledger/tips/pull/38) has been updated from `uint16` to `uint8`.

Output models should be updated in bee-message crate.

## Motivation
https://github.com/iotaledger/tips/discussions/60

## Requirements

Write a list of what you want this feature to do.

1. All outputs define `Native Tokens Count` as `uint8`

## Are you planning to do it yourself in a pull request?
No.

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/bee/pull/1036
