### ISSUE TITLE
Remove DUST_DEPOSIT_MIN const

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/bee#1043]
## Bug description

https://github.com/iotaledger/bee/blob/26f4b3de79b69e99430abe5e3073a39ca8e33f39/bee-message/src/constant.rs#L9 should be removed, because it's not a constant value anymore

**Comment by NaincyKumariKnoldus** [comment]
Hey @Thoralf-M Can I do this please?

**Comment by Thoralf-M** [comment]
From my side yes, or have you already done something in another branch @thibault-martinez?

**Comment by thibault-martinez** [comment]
I did not. I believe the protocol parameter TIP will be updated with whether each parameter is constant or configurable, I would personally wait for that before doing it. How were you planning on replacing it ?
