### ISSUE TITLE
Add plugins field to InfoResponse

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/bee#1066]
## Description

Add plugins field to InfoResponse

## Motivation

It's here https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml

## Are you planning to do it yourself in a pull request?

No.

**Comment by samuel-rufi** [comment]
Done in https://github.com/iotaledger/bee/pull/1099
