### ISSUE TITLE
Recent Changes in Stardust

### ISSUE THREAD

**Issue by lzpap** [iotaledger/bee#1084]
## Description
Several changes have been implemented in the Stardust specifications, namely:

[TIP-18](https://github.com/iotaledger/tips/pull/38)
 - [x] Renaming `Extended Output` to `Basic Output` (https://github.com/iotaledger/bee/pull/1074)
 - [x] Adding `Immutable Blocks` field to UTXO state machines (https://github.com/iotaledger/bee/pull/1128)
 - [x] Adding `Immutable Alias Address Unlock Condition` to foundry outputs (https://github.com/iotaledger/bee/pull/1101)

[TIP-20](https://github.com/iotaledger/tips/pull/40)
 - [x] Adding`Network ID` to the transaction essence for replay protection (https://github.com/iotaledger/bee/pull/1088)
 - [x] Adding `Inputs Commitment` field to tx essence (https://github.com/iotaledger/bee/pull/1125)

[TIP-22](https://github.com/iotaledger/tips/pull/43) is being updated via this [PR](https://github.com/Wollac/protocol-rfcs/pull/22)
 - [x]  `Network String` -> `Network Name` rename
 - [x] `Max Inputs/Outputs Count` is `128` (https://github.com/iotaledger/bee/pull/1076)
 - [x] `Max Native Token Count` is `64` (https://github.com/iotaledger/bee/pull/1103)
 - [x] `Max Metadata Length` is `8192` (https://github.com/iotaledger/bee/pull/1118)
 - [x] Added experimental `VByte Cost` for testnet of `500`

[TIP-24](https://github.com/iotaledger/tips/pull/55) is being updated via this [PR](https://github.com/Wollac/protocol-rfcs/pull/21/files)
 -  [x] Removing `Network ID` from message and replacing it with `Protocol Version`. (https://github.com/iotaledger/bee/pull/1088)

**Comment by thibault-martinez** [comment]
@lzpap What's affected by `Network String -> Network Name rename` ?

**Comment by lzpap** [comment]
> @lzpap What's affected by `Network String -> Network Name rename` ?

Info endpoint if I'm not mistaken
