### ISSUE TITLE
Create CI action for dashboard submodule checkout

### ISSUE THREAD

**Issue by Adam-Gleave** [iotaledger/bee#1106]
The same steps are used for the submodule checkout procedure in 4 different places across 2 workflows, so it would probably be nicer if we took these steps and put them in their own (local) action. That way, if/when the path to the submodule changes (like in #1105), it just has to be changed in one place.

**Comment by thibault-martinez** [comment]
Is there no way to create a named step that we can reuse like a function?

**Comment by grtlr** [comment]
I think the best way forward would be to write a `build.rs` script that builds the dashboard once it lives in it's own crate. That way the dashboard would automatically be built if the `dashboard` feature is set. This would be great for users of the Bee because they would save themselves the additional steps.

**Comment by Adam-Gleave** [comment]
That's what I mean: it would be one step in each of the jobs that uses it right now. Since the steps are used in both the coverage and bigger CI file it will need to be in a separate .yml, but it wouldn't run as its own pass/fail workflow, just as a step in each workflow it's used in -- just as `actions/checkout@v2` is used as a step in every workflow.

**Comment by Adam-Gleave** [comment]
> I think the best way forward would be to write a `build.rs` script that builds the dashboard once it lives in it's own crate. That way the dashboard would automatically be built if the `dashboard` feature is set. This would be great for users of the Bee because they would save themselves the additional steps.

Yes, I think this would be ideal actually 👍

**Comment by grtlr** [comment]
Closing in favor of #1144.
