### ISSUE TITLE
Add `Display` impl for `Address`

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/bee#1111]
## Description

Add a `Display` impl for address that is compatible with the `FromStr` impl.

## Motivation

Convenience and consistency.

## Requirements

Write a list of what you want this feature to do.

1. Allow converting `Address` to a string representation.
2. Allow parsing that string back to an `Address`.

## Open questions

Should this use the bech32 representation, or can the address types be represented/parsed according to their individual `Display` impls?

## Are you planning to do it yourself in a pull request?

No, rekt

**Comment by Thoralf-M** [comment]
The problem with the bech32 representation is that you need to define the human readable part `iota`, `atoi`... so it would only work for one

**Comment by grtlr** [comment]
Related: #1158

**Comment by grtlr** [comment]
We have removed the `FromStr` impl, because it could cause confusion as there could also be a hex representation of addresses. Further, taking @Thoralf-M's remark into consideration, `Display` probably would not make much sense here.

Feel free to reopen, if you feel otherwise 😃!
