### ISSUE TITLE
Better convenience functions for outputs

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/bee#1117]
## Description

The output variants have convenience functions, but they can be improved.

## Requirements

- [x] The `feature_blocks` and `unlock_conditions` methods should return `FeatureBlocks` and `UnlockConditions` structs respectively, so that the user can access their methods.
- [x] `BasicOutput` should have `sender` and `tag` convenience functions which optionally return those values.
- [x] `AliasOutput` should have `sender` and `issuer` convenience functions which optionally return those values.
- [x] `NftOutput` should have `dust_return_address`, `sender`, `issuer`, and `tag` convenience functions which optionally return those values.

## Motivation

Convenience.

## Are you planning to do it yourself in a pull request?

Non s'il vous plait.

**Comment by thibault-martinez** [comment]
@Alexandcoats FYI I will not directly put these methods on the output but on the `UnlockConditions` and `FeatureBlocks`. You'll just have one indirection through `unlock_conditions` and `feature_blocks` methods. I think it makes more sense that mapping all combinations that can potentially change.
