### ISSUE TITLE
Bee tries to sync from milestone that is below the pruning index

### ISSUE THREAD

**Issue by shufps** [iotaledger/bee#1141]
## Bug description

Bee tries to sync from a milestone index that is below the pruning index - actually, the pruning index itself seems to be wrong.

From `/api/v1/info`:
```
  "latestMilestoneIndex": 2521696,
    "confirmedMilestoneIndex": 1333459,
    "pruningIndex": 552871,
```
Pruning is set to about 90 days:
```
[tangle]
[tangle.pruning]
enabled = true
delay = 259200
```
The logs report about:
```
Synchronizing from 552871 to 2522119: confirmed 1333459 (39%) and solid 1333459 (39%) - Requested 0 - Tips 0.
```
It seems, it's not possible that bee makes progress with syncing because the milestone is too old (milestone 552871 should be about 230days ago) and the network (mainnet) doesn't have enough history.

Except this, bee is working fine and solidifying new milestones but the status is `unhealthy` because it's never synced.

## Bee version

Two versions have been tested: 0.1.0 and 0.3.0-rc4

## Expected behaviour

Bee should respect the pruning setting in the config file, set the new pruning index correct, delete the old data and not try to sync from milestone 552871 but from the corrected pruning index.

## Actual behaviour

It's forever trying to sync.

**Comment by grtlr** [comment]
@Alex6323 Do you maybe know more about this? This is blocking devops from deploying Bee along with Hornet nodes.

**Comment by Alex6323** [comment]
I am investigating this asap.

**Comment by shufps** [comment]
@Alex6323 it's **not** urgent :blush: 

According to Thibault, the pruning index comes from the snapshot that was used to initialize the node. Probably there is nothing we could do except to use a newer snapshot. But snapshot is only read once when starting the node the first time. So probably we have to wipe the database to get Bee to sync again, right? :blush:

**Comment by shufps** [comment]
Bee 0.1.0 didn't support pruning, there is no way to get bee synced without starting it fresh from a new snapshot.

Issue is closed :blush:
