### ISSUE TITLE
Stardust: Update the JSON representation of address objects

### ISSUE THREAD

**Issue by lzpap** [iotaledger/bee#1155]
## Description

Update the json representation of address objects as per:
 -  API spec: https://github.com/iotaledger/tips/pull/57/commits/4d21415f40781ec15a012f5e2b87310e4add13d1
 - Output spec: https://github.com/iotaledger/tips/pull/38/commits/b89d0f71b4865fe3c08d5777c6fda17c91b948f8

Example change in iota.go: https://github.com/iotaledger/iota.go/pull/315

**Comment by samuel-rufi** [comment]
Thanks for the issue! @lzpap

**Comment by samuel-rufi** [comment]
Fixed with https://github.com/iotaledger/bee/pull/1157
