### ISSUE TITLE
Switch `documentation/` over to `config.json`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/bee#1200]
Currently, the documentation (IOTA Wiki) is still using the `config.toml` format, but we now support `config.json` as our main format.

@Dr-Electron could you change this please?

**Comment by Dr-Electron** [comment]
Sure

**Comment by Dr-Electron** [comment]
Would something like this work?

<img width="825" alt="Bildschirmfoto 2022-03-05 um 00 15 03" src="https://user-images.githubusercontent.com/61637085/156854697-6e1dcfcd-5d91-4b8c-8268-1d48ace7a5e0.png">

**Comment by grtlr** [comment]
Yeah, I think this is awesome! Is it a lot of work?

**Comment by Dr-Electron** [comment]
No, it wasn’t really a lot of work 😅 . Check the branch

**Comment by grtlr** [comment]
Are you still looking into this @Dr-Electron? Otherwise, I would merge this soon so that we can release `v0.3`.

**Comment by Dr-Electron** [comment]
What do you mean? This can be closed as it was already merged, right?

**Comment by grtlr** [comment]
You're right, sorry I lost track there 😅
