### ISSUE TITLE
Update `SimpleTokenScheme` and API

### ISSUE THREAD

**Issue by grtlr** [iotaledger/bee#1269]
Changes to:
- TIP-18: https://github.com/iotaledger/tips/pull/38/commits/4257b772cab90178832ad7f43fa60d6cdd1ddc85
- TIP-25: https://github.com/iotaledger/tips/pull/57/commits/83dd9f679179b856c2316d4fb9f5d3cff75566dd

@thibault-martinez Will this be part of #977?

**Comment by thibault-martinez** [comment]
I'll do it when #977 is merged.
