### ISSUE TITLE
Skip values that are set to `0` in dto serialization

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/bee#1275]
## Description

For example unixTime in an expiration unlock condition, is now skipped during the serialization if it's set to 0

## Motivation

Compatibility

## Requirements

1. Make these fields optional https://github.com/iotaledger/iota.go/commit/ee47d60a05b076647b6b47e95535d5de081d278b

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Go's `omitempty` also considers `0` as "empty" ?

**Comment by Thoralf-M** [comment]
Yes
