### ISSUE TITLE
Node: Add a `developer` mode to Bee (--feature dev), which collects live performance metrics

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/bee#292]
Currently we use the dashboard to get a rough idea about how the node performs. But this is inaccurate and inefficient, because it has to be sent through websockets and then be rendered. Also it is limited. A developer mode behind a feature flag can produce much more relevant and accurate data to base decisions on.

**Comment by thibault-martinez** [comment]
Not necessarily a developer mode but we'll probably do a prometheus plugin like HORNET has at some point.

**Comment by thibault-martinez** [comment]
Won't do given the new priority of the bee node.
