### ISSUE TITLE
called `Option::unwrap() during snapshot import

### ISSUE THREAD

**Issue by svenger87** [iotaledger/bee#309]
`Jan 26 10:14:53 iota-comnet-node bee[1434124]: [2021-01-26][10:14:53][bee_snapshot::worker][INFO] Importing full snapshot file ./snapshots/alphanet/full_snapshot.bin...
Jan 26 10:14:53 iota-comnet-node bee[1434124]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /opt/bee/bee-tangle/src/worker.rs:69:93`

Snapshot folder was deleted before starting the application.

**Comment by svenger87** [comment]
`[2021-01-26][11:08:37][bee_snapshot::worker][INFO] Importing full snapshot file ./snapshots/alphanet/full_snapshot.bin...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /opt/bee/bee-tangle/src/worker.rs:69:93
stack backtrace:
   0:     0x55b54d947000 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x55b54d947000 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b54d947000 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b54d947000 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b54d96a12c - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x55b54d93f572 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x55b54d949485 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b54d949485 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b54d949485 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x55b54d949128 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x55b54d949c21 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x55b54d949737 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:497:13
  12:     0x55b54d9474bc - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b54d9496c9 - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x55b54d968031 - core::panicking::panic_fmt::ha0bb065d9a260792
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:     0x55b54d967f7d - core::panicking::panic::h339b30ca166fd852
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
  16:     0x55b54d023bd3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h183469245aee2106
  17:     0x55b54d06829f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he4aa19f26f64fc0a
  18:     0x55b54cff51a0 - <bee_node::node::builder::BeeNodeBuilder<B> as bee_runtime::node::NodeBuilder<bee_node::node::BeeNode<B>>>::finish::__finish::{{closure}}::h7bb2489dad2fdf9e
  19:     0x55b54d0247c3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1d9dbdfa6f7a9e03
  20:     0x55b54d026f73 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2d36d1c11e4d348a
  21:     0x55b54d19685f - tokio::park::thread::CachedParkThread::block_on::h93489aeb8b922ffb
  22:     0x55b54cfdc617 - tokio::runtime::thread_pool::ThreadPool::block_on::h07322a5a6243b4ae
  23:     0x55b54cf88a08 - tokio::runtime::Runtime::block_on::h67b9160f0821c1e4
  24:     0x55b54d182530 - bee::main::h04f4d1cac1188d1c
  25:     0x55b54d1d8663 - std::sys_common::backtrace::__rust_begin_short_backtrace::h84ffb9ea077fd7f8
  26:     0x55b54d1d8679 - std::rt::lang_start::{{closure}}::ha186a41daa1c80b9
  27:     0x55b54d94a137 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  28:     0x55b54d94a137 - std::panicking::try::do_call::h81cbbe0c3b30a28e
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  29:     0x55b54d94a137 - std::panicking::try::hbeeb95b4e1f0a876
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  30:     0x55b54d94a137 - std::panic::catch_unwind::h59c48ccb40a0bf20
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  31:     0x55b54d94a137 - std::rt::lang_start_internal::ha53ab63f88fee728
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  32:     0x55b54d1825f2 - main
  33:     0x7fea9bcb00b3 - __libc_start_main
  34:     0x55b54ced491e - _start
  35:                0x0 - <unknown>`

**Comment by thibault-martinez** [comment]
We need to better handle snapshot parsing errors.
Read both headers from the worker, otherwise panics from the spawned task.

**Comment by thibault-martinez** [comment]
This has been fixed.
