### ISSUE TITLE
Websocket error and dashboard empty

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/bee#338]
## Bug description

Sometimes I get a empty dashboard with only the dark blue background.

## Rust version

- Rust version: 1.49.0

## Bee version

- Bee version:  f6dc59a

## Hardware specification

- Operating system: Ubuntu 20.04
- RAM: 4GB
- Cores: 3 vCores
- Device: VPS

## Errors

`[2021-01-30][23:43:08][bee_node::plugins::dashboard::websocket][ERROR] websocket error(uid=1): WebSocket protocol error: Connection reset without closing handshake`
`[2021-01-31][00:00:06][bee_node::plugins::dashboard::websocket][ERROR] websocket error(uid=23): IO error: Connection reset by peer (os error 104)`
`[2021-01-31][00:00:06][bee_node::plugins::dashboard::websocket][ERROR] websocket send error: IO error: Broken pipe (os error 32)`

**Comment by turnikuta** [comment]
Got the same problem
```
2021-04-14 10:20:49 bee_node::plugins::dashboard::websocket    ERROR websocket error(uid=11): WebSocket protocol error: Connection reset without closing handshake
```
with
Bee: 0.1.0-alpha-28d5d86  (testnet7)
Rust: 1.51.0 (2fd73fabe 2021-03-23) 

Remark:
I had in the meantime an "Out of Memory" problem (bee memory usage > 8GB). Probably this is related to that.

**Comment by samuel-rufi** [comment]
The author hasn't noticed the issue anymore.
