### ISSUE TITLE
Visualiser „broken“ in current release - Testnet 3

### ISSUE THREAD

**Issue by kranebitt** [iotaledger/bee#358]
## Bug description

The visualizer seems not to work properly.

![5E251712-A402-4BC4-AA3B-A225080F4F7B](https://user-images.githubusercontent.com/47479898/106806594-73c73880-6668-11eb-8211-a0ff158ac485.jpeg)

**Comment by Alex6323** [comment]
Did you make sure you run the most up-to-date dashboard?

**Comment by Dr-Electron** [comment]
I seem to have the same problem. Pretty sure I'm on the newest version

**Comment by kranebitt** [comment]
I updated it today at about 7 pm

**Comment by Alex6323** [comment]
alright, thanks guys

**Comment by samuel-rufi** [comment]
really interesting, vertices aren't connected. thanks for the issue.
