### ISSUE TITLE
Dashboard Explorer can't display Message 

### ISSUE THREAD

**Issue by turnikuta** [iotaledger/bee#391]
## Bug description

Dashboard Explorer can't display Message 4099d730fd84de1cdc208b03dec55425d579d3f12c57e5d513feeae030c993cd.

## Rust version

Which version of Rust are you running?

- Rust version:  - rustc 1.49.0 (e1884a8e3 2020-12-29)
- Node version: - v10.23.2

## Bee version

Which version of Bee are you using?

- Bee version (version number, commit, or branch):  0.1.0-alpha-e5b45a6

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 18.04.5 LTS (Hetzner VPS)
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Seach for specified MessageId in Dashboard Explorer 
2. 
3. 

## Expected behaviour

Display of the attributes of the corresponding message

## Actual behaviour

Nothing is displayed.

## Errors
Debug Mode of the Explorer shows:
```
TypeError: r[u] is undefined
    a TransactionPayload.tsx:45
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value AsyncComponent.tsx:36
    e Message.tsx:75
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    Babel 6
    value main.3925093a.chunk.js:1
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value AsyncComponent.tsx:36
    e Search.tsx:143
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    Babel 6
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react-dom.production.min.js:216:199
```

**Comment by thibault-martinez** [comment]
I believe this has been fixed, re-open if not the case.
