### ISSUE TITLE
Dashboard authentication

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#392]

**Comment by obany** [comment]
Changes required to add auth to dashboard (public mode shows only explorer and visualizer + health indicators / mps in header)

POST `/login` endpoint should accept JSON 

```json
{
   "user": ".......",
   "pass": "......."
}
```

or for an already authenticated user, returning to the dashboard the endpoint will be sent.

```json
{
   "jwt": "......."
}
```

On a successful login should return:

```json
{
   "jwt": "......."
}
```

Websocket endpoints are now split into 2 categories, public and private.

Public topics are subscribed the same way as current process [0]=register, [1]=topic.
Private topics have a larger buffer with bytes [0]=register, [1]=topic, [2...n]=jwt

The `NodeStatus` topics has been split into public and private data, all field names are the same.

Private https://github.com/iotaledger/node-dashboard/blob/feature/chrysalis-pt2-auth/src/models/websocket/INodeStatus.ts
Public https://github.com/iotaledger/node-dashboard/blob/feature/chrysalis-pt2-auth/src/models/websocket/IPublicNodeStatus.ts

The topic indexes have been modified to include the new public/private node topics https://github.com/iotaledger/node-dashboard/blob/feature/chrysalis-pt2-auth/src/models/websocket/webSocketTopic.ts

Public Topics which are always accessible

SyncStatus
PublicNodeStatus
MPSMetrics
Ms
ConfirmedMsMetrics
TipInfo
MilestoneInfo
ConfirmedInfo
SolidInfo
Vertex

Private Topics which should only be accessible with a valid jwt

NodeStatus
DBSizeMetric
PeerMetric
SpamMetrics
AvgSpamMetrics

**Comment by obany** [comment]
Quick update the endpoint is now `/auth` instead of `/login`, as it caused problems with the `/login` route within the app (one doing GET and the other POST).

Also CSRF protection is optionally enabled as well, since the POST and DELETE methods for peers is now used. So if your web middleware sends a `_csrf` cookie it will be returned in the `X-CSRF-Token` header on any calls to the APIs.
