### ISSUE TITLE
Tracking issue for open RFC: implement EEE crate

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/bee#42]
This is a tracking issue for the open RFC “e3 protocol for bee” ([iota-ledger/bee-rfcs#2](https://github.com/iotaledger/bee-rfcs/pull/2)).

**Comment by wusyong** [comment]
The explanation is very detailed! Thanks! Since this is an epic maybe it's a good idea to open issue for each subject and link to here. 

Regarding **Effect**, how about make this a trait? We implement this trait to the type we want and we can also use trait bound and trait object in this way.

**Comment by Alex6323** [comment]
We were having many discussions about how to best model **Effect** in previous chats in the Discord channel, which lead to Lukas to the idea of *typed supervisors*. I can't repeat everything here, but there are several reasons why this idea would be unhandy atm to pursue. I'm not saying that this is not a valid solution, but since it's definitely more complex, I'ld say we start with something more simple like the enum solution.

The way I see it is that an *Effect* is an abstraction over different datatypes (you want to be able to send floats, integers, bytes, you name it), but not an abstraction over behavior which traits provide.

That's why you're basically limited to pursoue on of three solutions:
* using enums
* using generics
* using runtime reflection

I am willing to try any of those possible solutions. I favor starting out simple (enum), see where the limitations are and then switch to another rather than shooting with canons right away.
