### ISSUE TITLE
bee node stops solidifying while neighbors are synced

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/bee#422]
## Bug description

node _4c45559_ stopped solidifying at LSMI/LMI 10029 / 10340 - 1 hornet-pt2 and 2 bee neighbors remained in sync

## Rust version

rustc 1.50.0 (cb75ad5db 2021-02-10)

## Bee version

4c45559 (HEAD -> chrysalis-pt-2, origin/chrysalis-pt-2) Use actual peer alias when reconnecting and dialing

## Hardware specification

- Operating system: ubuntu 20.04 LTS
- RAM: 16 GB
- Cores: 4 
- Device: ESXi VM

## Steps To reproduce the bug

not sure. this has happened several times with several previous versions of the node during running testnet4, and
 has now happened on a testnet5 version

## Expected behaviour

node to remain in sync

## Actual behaviour

node falls out of sync

## Errors

this was at MS 6063 (see log), but node kept solidifying after that

`2021-02-19 22:13:28 bee_ledger::worker                         [91mERROR[0m Confirmation error on 6c6131ecad6f7821f99f60c2079df6d2f982414a9a8cc662e13f87e47227350a: Message d991db908271756ff37b37563f6445c0efb118d75d51daff07624ecd0abccf60 is missing in the past cone of the milestone.
thread 'tokio-runtime-worker' panicked at 'Aborting due to unexpected ledger error.', /opt/bee/bee-ledger/src/worker.rs:313:21`

node falls out of sync at MS 10029, nothing unusual in the log

[bee.log](https://github.com/iotaledger/bee/files/6015961/bee.log)

<img width="1024" alt="node falls out of sync" src="https://user-images.githubusercontent.com/10619487/108604865-42878180-7365-11eb-935b-fba8faa0fc49.png">

**Comment by QNODE-CA** [comment]
after removing database / snapshot and restarting, node fell out of sync  again 11295 / 12025

new log:

[bee2.log](https://github.com/iotaledger/bee/files/6016820/bee2.log)

**Comment by QNODE-CA** [comment]
node was in sync for about 2 days, recently out of sync on ms 36329.   adding log (debug) from starting the node


[bee-debug-0.1.0-alpha-4c45559.log.zip](https://github.com/iotaledger/bee/files/6031190/bee-debug-0.1.0-alpha-4c45559.log.zip)

there *could* be a relationship between a know neighbor gossip port not being reachable and bee node going out of sync

**Comment by thibault-martinez** [comment]
This has been fixed.
