### ISSUE TITLE
Dashboard indicates node is still healthy, although the ledger worker panicked.

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/bee#435]
## Bug description

Expected behavior:
Dashboard shows that the node is not healthy anymore once a critical worker like the ledger worker has panicked.

Actual behavior:
The Bee logs show that the ledger worker panicked. The dashboard however still indicates that the node is healthy.

## Rust version
latest

**Comment by thibault-martinez** [comment]
That was because `is_healthy` was using SMI instead of CMI, this has been fixed here https://github.com/iotaledger/bee/commit/ecf4c9195dc514482080a999539754c8e2dce97e.
