### ISSUE TITLE
Bee doesn't handle SIGTERM signal

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/bee#510]
## Bug description

Sending a SIGTERM signal doesn't shut down.

## Bee version

Which version of Bee are you using?

- Bee version: commit `9ecc49a1cb5d56d7a27ea388ed8787790724e40c` 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Run docker image using docker-compose
2. do `docker-compose down -t 180`
3. you will see docker will hang for a long while because the SIGTERM signal is ignored -> bug

--- it is probably easier for the replicator to just run without docker and do a simple `kill <pid>`. I just wrote the steps I used.

## Expected behaviour

Bee should shutdown gracefully

## Actual behaviour

Bee continues to run

**Comment by Adam-Gleave** [comment]
Thanks, I'll take a look at this.
