### ISSUE TITLE
Bee panics if there is no delta snapshot

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/bee#514]
## Bug description

If we load a bee node with just the full snapshot and no delta it panics

## Bee version

Which version of Bee are you using?

- 87d7973

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Start isolated bee with only full snapshot

## Expected behaviour

Bee should load

## Actual behaviour

Bee panics

## Errors

```
bee    | 2021-04-14 12:53:49 bee_ledger::snapshot::import               INFO  Importing delta snapshot file ./snapshots/mainnet/delta_snapshot.bin...
bee    | thread 'main' panicked at 'Worker `bee_ledger::consensus::worker::LedgerWorker` failed to start: Snapshot(UnsupportedVersion(1, 60)).', /bee/bee-node/src/node/builder.rs:130:35
bee    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by thibault-martinez** [comment]
Should be fixed now
