### ISSUE TITLE
UnexpectedDiffIndex

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/bee#520]
## Bug description

Tried to run Bee in a private Tangle setup. Somehow Bee seems to have problems with a snapshot provided from a Hornet node.

- Bee version (version number, commit, or branch): 7b955c9

## Errors

thread 'main' panicked at 'Worker `bee_ledger::consensus::worker::LedgerWorker` failed to start: UnexpectedDiffIndex(MilestoneIndex(107328)).', /root/bee/bee-node/src/node/builder.rs:130:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by thibault-martinez** [comment]
I think this has been fixed.
