### ISSUE TITLE
Minor issue: statement that node is offline when refreshing dashboard

### ISSUE THREAD

**Issue by kranebitt** [iotaledger/bee#585]
## Bug description
When loading/refreshing the node dashboard in my (mobile) browser it wrongly states that the node is offline - even when it isn‘t. 

## Bee version

0.1.1-bee3eac

## Hardware specification

What hardware are you using?

iPhone / Safari

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Load the node dashboard via Safari web browser or refresh a current tab with the dashboard.
2. The error message instantly appears while loading.
3. Then the Dashboard loads correctly.

## Expected behaviour

To get a message like: „Currently loading node dashboard“

## Actual behaviour

It looks like the node were down, even when it isn‘t.

## Errors

![386B863C-FB52-4C50-ADA4-801A4A0B8363](https://user-images.githubusercontent.com/47479898/118394408-ddca8300-b644-11eb-85ec-c119b4503a76.jpeg)

**Comment by thibault-martinez** [comment]
Hi @kranebitt, thanks for the report. It's actually not possible to know if the node is currently loading or completely offline. We improved the message anyway here https://github.com/iotaledger/node-dashboard/pull/45, is that fine ?

**Comment by kranebitt** [comment]
Great. To me it‘s clear now.
