### ISSUE TITLE
MultiFetch to return Vec<Result<Option<_>>> ?

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#614]

**Comment by pvdrz** [comment]
Could it be reasonable to have an API that returns `impl Iterator<Item = Result<Option<_>>>`? This would avoid doing allocations at the cost of having to iterate yourself.

**Comment by thibault-martinez** [comment]
I think it's reasonable, we already return a stream for `AsStream` so requiring the user to iter is fine.

**Comment by pvdrz** [comment]
I think the only issue is how you avoid requesting each tree/column family for every element in your request. I don't know if lifetimes are enough for this.
