### ISSUE TITLE
Download only the latest snapshot from the list of snapshot sources

### ISSUE THREAD

**Issue by no8ody** [iotaledger/bee#757]
When downloading a snapshot, Bee should only use the source that has the latest snapshot. This is already the case in Hornet.

https://github.com/gohornet/hornet/blob/ecdb18b0f8ea6a775807e1159e908d28a1ae0363/pkg/snapshot/download.go

**Comment by grtlr** [comment]
Thanks for filing this issue 💪 ! The functionality has been implemented in PR #780.
