### ISSUE TITLE
Breaking changes and deprecations

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#831]
As we commit to stability of our crates, we are not able to do some changes we would like to do.
We are given a window to perform all of our desired changes with the tokenization framework release which is protocol breaking.
This issue collects all breaking changes and deprecations that should be packed with it.

- [x] Switch to new Packable version (#796)
- [x] Remove deprecated hash/sign functions
  - [x] Remove internal `CurlP` variants
  - [x] Figure out strategy for `BatchHasher` and `UnrolledCurlP81`, ideally we can get rid of `bee-crypto` entirely (#829).
  - [x] Remove `Sponge` and `SpongeKind`
  - [x] Remove `bee-signing` crate

**Comment by pvdrz** [comment]
The switch to packable is being handled here: https://github.com/iotaledger/bee/pull/796

**Comment by grtlr** [comment]
`CurlP27` and `Kerl` are deprecated by #826. In the future, we will also use `CurlP` from `iota-crypto` instead of `bee_crypto::CurlP81`. We will have to decide what to do with `BatchHasher` and `UnrolledCurlP81`.

**Comment by pvdrz** [comment]
I am almost certain what we can remove `BatchHasher` there's basically no use for it given that `UnrolledCurlP81` is almost as fast without needing batching.

**Comment by grtlr** [comment]
I think this can be closed now, right?
