### ISSUE TITLE
Improvements to the CI

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#854]
- [ ] Only triggers when Rust or Cargo.toml/lock files are changed
- [ ] Investigate why crates are being recompiled even when cache has been recovered
- [ ] Merge check and test workflows ?

**Comment by grtlr** [comment]
Regarding the first point: don't forget `Cargo.lock` files

**Comment by grtlr** [comment]
We had some discussion about using [action composition](https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/) to reduce the number of builds that we have to do. The basic idea is to have a `build` job, on which the other jobs like `check`, `test` depend on. I don't know if these jobs actually share the same machine though.

**Comment by grtlr** [comment]
Reading some more, I think multiple jobs per workflow are more what we want: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idneeds. Although, these jobs also seem to have individual instances.

**Comment by grtlr** [comment]
I will adapt the CI for the `coordicide` branch too. Until then, we can keep this issue open.

**Comment by grtlr** [comment]
This has been fixed with #856 in `dev` and with #860 in `coordicide`.
