### ISSUE TITLE
Panic while trying to import the delta snapshot file [cpt2 branch]

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/bee#948]
# Bug description

When trying to run the node from the "chrysalis-pt-2" branch, sometimes the node crashes while trying to import the delta snapshot file:

```bash
2022-01-13 07:54:47 (UTC) bee_ledger::workers::snapshot::import      INFO  Importing delta snapshot file ./snapshots/mainnet/delta_snapshot.bin...
thread 'main' panicked at 'Worker `bee_ledger::workers::snapshot::worker::SnapshotWorker` failed to start: Types(UnsupportedVersion(1, 60)).', /root/bee/bee-node/src/fullnode/builder.rs:103:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: “../target/release/bee” terminated by signal SIGABRT (Abort)
```
Printing the delta snapshot file with `cat ./snapshots/mainnet/delta_snapshot.bin` yields:

```html
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by grtlr** [comment]
To reproduce this problem locally, point `[[snapshot.download_urls]].delta` in the `Config.toml` to an invalid URL.

PR #949 should fix this problem by properly handling the status codes of the server's response.
