### ISSUE TITLE
Logs cleanup and harmonisation

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#956]
- [x] The PeerId / Local is logged twice
- [x] Replace `WARNING` for autopeering with `DISCLAIMER`
- [x] `Flushing data to peer store...` shouldn't be INFO
- [x] The network ID as number is probably useless
- [x] Align autopeering warning dashes
- [x] Most of the autopeering info (protocol version, public key, address, ...) shouldn't be INFO

**Comment by grtlr** [comment]
Maybe it would also help to define what each of the levels stand for. Currently we are using the following log levels: `error`, `warn`, `info`, `debug`, and `trace`.

`error` and `warn` are probably self-explanatory, but the distinction between `debug` and `info` is a bit trickier. In my opinion, `info` should only contain messages that are essential to the user. Here is a list of things that I think fit the `info` level well:

* `2022-01-24 13:29:19 (UTC) bee_node::fullnode::builder                INFO  Joining network "chrysalis-mainnet"(1454675179895816119). Bech32 hrp "iota".`
* `2022-01-24 13:29:19 (UTC) bee_node::fullnode::builder                INFO  PeerId: 12D3KooWSEaafBZ6LjTdr2EvtpbmxpVoqHYZHLcFfEC6wUZdPqCM, Alias: bee`
* `2022-01-24 13:29:19 (UTC) bee_ledger::workers::snapshot::worker      INFO  Loaded snapshot from 2022-01-18 10:53:33 (UTC) with snapshot index 2280928, entry point index 2280928 and pruning index 2280928.`

But the log also contains things that are less important to the user:

* `2022-01-24 13:29:19 (UTC) bee_protocol::workers::requester::message  INFO  Retryer running.`
* `2022-01-24 13:29:20 (UTC) bee_protocol::workers::message::processor  INFO  Running.`
* `2022-01-24 13:29:32 (UTC) bee_protocol::workers::message::submitter  INFO  Stopped.`

One thing that's common to these is that they notify about the state of certain subcomponents of Bee. However, most users don't even know what these components are, so maybe we should move those to debug?

**Comment by Adam-Gleave** [comment]
>  In my opinion, info should only contain messages that are essential to the user

Definitely agree, although I guess not necessarily *essential* to the user, but they should be something the user might want and would understand. The second group there look more appropriate for debug logs to me.
