### ISSUE TITLE
Bee doesn't stop

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/bee#985]
## Bug description

If I stop my bee service not all plugins get stopped and I can wait for more than 15min but Bee still doesn't stop...

## Rust version

- Rust version: 1.57.0

## Bee version

- Bee version (version number, commit, or branch): 7fbbfabb

## Hardware specification

- Operating system: Ubuntu
- RAM: 4GB
- Cores: 3 
 
## Steps To reproduce the bug

Stop Bee

## Errors

[bee_logs.txt](https://github.com/iotaledger/bee/files/7892715/bee_logs.txt)

**Comment by Alex6323** [comment]
Bee is like the terminator....It won't stop until you're .... :trollface:

**Comment by pvdrz** [comment]
user: Ctrl+C
bee: https://www.youtube.com/watch?v=HgzGwKwLmgM

**Comment by Dr-Electron** [comment]
[none_stopping.log.zip](https://github.com/iotaledger/bee/files/7929054/none_stopping.log.zip)

You wanted TRACE, you get TRACE :trollface:

**Comment by thibault-martinez** [comment]
From these logs, it appears that https://github.com/iotaledger/bee/blob/chrysalis-pt-2/bee-node/src/plugins/dashboard/workers/peer_metric.rs#L47 is never logged, suggesting that the loop before never finished.

**Comment by pvdrz** [comment]
@Dr-Electron this last PR should fix the issue, can you check if it works as expected from your end when you have time?

**Comment by Dr-Electron** [comment]
Seems fine to me 🤔 No problems until now
